# Generated by Django 4.0.2 on 2023-11-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
